### ISSUE TITLE
I can compile the code in VS2015, Windows, but the run result seems wrong.

### ISSUE THREAD

**Issue by oya123** [taketwo/radical#6] opened 2017-07-31 03:48 UTC
I compile and run the code both in Linux and Windows. In Linux it looks good.
In Widnows, I tried tow methods to compile it: 
1) modify CMakelists.txt , CMake 3.9 + Visual Studio 2015 to compile it.
2) Just use Visual Studio 2015, manually add the 3rd libraries.
These two methods both can help me compile code successfully.
But when I run the code, the results seems wrong.
Here is the output of calibrate_radiometric_response in Windows and Ubuntu.
![image](https://user-images.githubusercontent.com/22723463/28762121-854e95a6-75e6-11e7-8791-af488f7e76e9.png)

![image](https://user-images.githubusercontent.com/22723463/28762287-d62419c8-75e7-11e7-877f-b2533b56c962.png)

![image](https://user-images.githubusercontent.com/22723463/28761930-01489258-75e5-11e7-9bc5-95aa3d334203.png)

When I just use radical library, it cannot show the image, the output cv::Mat it black.
![image](https://user-images.githubusercontent.com/22723463/28762053-fd1834f8-75e5-11e7-9615-f6c299404d6e.png)

Could you give me some suggestion to solve the problem above?
Thanks for your advice.

**Comment by taketwo** [comment] 2017-07-31 06:54
Hi, thanks for the interest. It looks like on Windows the calibration process does not converge. Trying to compile and test on Windows has long been in my TODO list, I hope I can give it a try and find the problem soon.

Regarding the second part of your question, can you explain what exactly you are doing and what you expect to see?

**Comment by oya123** [comment] 2017-07-31 07:08
Thanks for your reply!
In the second part of my question, I use the radical as a library like you described in README.txt . Right image is the original  color image from Xtion RGBD sensor, and left image is output image with vignette removed.
The source is:
```
cv::Mat frame;                 //  color image from the camera`
cv::Mat irradiance, radiance;  // temporary storage
cv::Mat frame_corrected;       // output image with vignette removed
rr.inverseMap(frame, irradiance);
vr.remove(irradiance, radiance);
rr.directMap(radiance, frame_corrected);
```

The calibration files used for this code is the calibration results that from the Ubuntu. And this code looks good in Ubuntu.  **frame_corrected** in Windows is black.

**Comment by taketwo** [comment] 2017-07-31 07:50
Oh, I see. Seems like something is really broken in Windows. I will have a look very soon and let you know.

**Comment by taketwo** [comment] 2017-08-01 14:19
Hey, I've pushed some updates that allow to compile the library and the apps in VS2015 out of the box.
Further, I've found and fixed the reason for the black image (problem with serialization of vignetting response calibration file on Windows platform, these bloody line endings :)) 
Finally, I've added a new app for quick testing that just removes vignetting effects from images of camera stream. It's called `remove_vignetting`, give it a try.

The problem with non-converging calibration is still present, I can reproduce it but haven't had time to look into that.

**Comment by oya123** [comment] 2017-08-02 03:34
Thanks a lot!
I've try the new code and the black image problem has been solved!
I can only calibrate the sensor in Ubuntu and run the result in Windows. But it's not hard to do.

**Comment by taketwo** [comment] 2017-08-02 06:48
Glad to hear. I'll check what's going on with the "engel" calibration on Windows at some later point. In the meanwhile, one more option (besides calibration on Linux) is to use "debevec" calibration. To enable it, you need to compile with Ceres.

**Comment by taketwo** [comment] 2017-10-21 18:13
There was a problem with energy computation after rescaling on each iteration. Should be fixed now.

**Closed as completed by taketwo** 2017-10-21 18:13 UTC
Labels: bug, windows
