### ISSUE TITLE
calibrate_radiometric_response: Nothing happens when using pre-recorded dataset

### ISSUE THREAD

**Issue by LukeOrgana** [taketwo/radical#11] opened 2018-08-04 05:13 UTC
I have pre-recorded a radiometric response dataset using a Basler acA2040-25gmNIR (grayscale) GigE camera. I have 15 images starting with an exposure time of 1ms and increasing up to 10000ms with a factor of 2 increase in exposure time between each image.

When I run the following command, nothing happens.

`./calibrate_radiometric_response --exposure-min 1 --exposure-max 10000 -o BaslerCRF.crf --method debevec -v 2 --print -f 2 ~/ImageDatasets/VignettingCalibration/crfCalImgs/`

I get a blank window open up, with the title "Calibration". In stdout I get "Loaded dataset from: ~/ImageDatasets/VignettingCalibration/crfCalImgs/"...

...and then nothing. I thought I would see some images in the window, but the window remains blank. However, I am not sure if this is what is supposed to happen, as I have not run the program before.

But If I now press enter, it says its starting the Debevec calibration procedure, and then seg faults.

Could this be because the images are grayscale ppm images, but colour images are expected? Or could it be related to the fact that when I run the tests (i.e. `make tests`) it fails on the calibrate_radiometric_response test? Or is there something I am just not understanding?

**Comment by LukeOrgana** [comment] 2018-08-04 11:49
I have also tried converting my images to .mat using the writeMat() function. Still nothing happens until I press Enter, and then it seg faults like before.

**Comment by taketwo** [comment] 2018-08-05 02:20
Hi, first of all, regarding what should happen. In the beginning you should see a plot demonstrating distribution of pixel intensities in the collected dataset. Then, after hitting enter, optimization process will begin. There are some test data checked into Git LFS of this repository (under `tests/data/radiometric_response_calibration`) which you can use to get an impression of the process. So pull the data and try the following from the repository root:

```bash
./build/bin/calibration_radiometric_response tests/data/radiometric_response_calibration
```

Now as for `make tests`, this should not fail. Does it say anything specific about what fails? Maybe it's because you did not pull the test calibration data.

Finally, regarding your camera and grayscale images. Most likely this is the cause of the troubles. I've never tested/used calibration with grayscale images. While implementing the calibration program and algorithms I put reasonable effort into implementing everything in the number-of-channels agnostic way, however it could well be that somewhere I forgot and explicitly assumed 3 channels. Or there may be a bug specific to 1-channel case which was never caught because I did not test for it. I guess my suggestion for you would be to compile in debug mode and check the backtrace of the segfault or even run step-by-step with debugger.

**Comment by LukeOrgana** [comment] 2018-08-05 03:04
Hi. Thank you for your reply. I have the test data, so I tried your suggestion from the repository root directory. I have attached some screenshots of what happened. I also took a screen shot of the `make tests` output so you can see what happens.

![calibration_window](https://user-images.githubusercontent.com/24378630/43682187-703ae86c-9864-11e8-87bf-236d5fd95ede.png)
![segfault](https://user-images.githubusercontent.com/24378630/43682188-70581202-9864-11e8-852d-bbfb65648bc0.png)
![testoutput](https://user-images.githubusercontent.com/24378630/43682189-70740ee4-9864-11e8-9051-6f4709c601e7.png)

I will try to run the code in gdb to see if I can find where it is crashing. Thanks for your help.

**Comment by taketwo** [comment] 2018-08-05 03:14
Please double-check that you have the data. What I have tried just now is to wipe the contents of the `tests/data/radiometric_response_calibration` directory. Now I also get white window instead of a histogram and then a segfault. To get data you need to run `git lfs pull`.

**Comment by LukeOrgana** [comment] 2018-08-05 04:33
After running `git lfs pull` and then `./build/bin/calibration_radiometric_response tests/data/radiometric_response_calibration` it now works as expected. It certainly looked like I had the data before, but on closer inspection the .mat files were 131 bytes each but now they are 921.6kB.

`make tests` now also works fine.

I still get the blank window and the segfault when I try to use my own dataset. So I guess it may well be because I am using grayscale images.

**Comment by LukeOrgana** [comment] 2018-08-05 05:41
The main issue I was having with my dataset was actually because I had not named my files correctly. By renaming my files to have the following format xxxxxx_000.mat, they were then loaded correctly. So that's my bad. Can I ask you to clarify that the first 6 digits represent the exposure time in ms? e.g. for an image with an exposure time of 10 ms, the file should be called 000010_000.mat?

The program proceeded to display the histogram (only one due to the single channel) and do the optimization, but then crashed when trying to write the output file because here I believe it expects three channels. This may not be how you would like to handle grayscale images, but the following changes in radical/mat_io.cpp  (and by adding `#include <opencv2/imgproc/imgproc.hpp` to mat_io.h) fixed the problem:

```
cv::Mat readMat(std::ifstream& file) {
    uint32_t magic, type, dims, rows, cols;
    file.read((char*)(&magic), sizeof(uint32_t));
    if (magic != MAGIC)
        throw SerializationException("File does not contain a cv::Mat");
    file.read((char*)(&type), sizeof(uint32_t));
    file.read((char*)(&dims), sizeof(uint32_t));
    if (dims > 2)
        throw SerializationException("File contains a cv::Mat that is not 1- or 2-dimensional");
    file.read((char*)(&rows), sizeof(uint32_t));
    file.read((char*)(&cols), sizeof(uint32_t));
    cv::Mat mat(rows, cols, type);
    assert(mat.isContinuous());
    file.read((char*)(mat.data), mat.elemSize() * mat.total());
    file.close();
    if ( mat.channels() == 1 ) {
        std::cout << "Loaded image is grayscale. Converting to color..." << std::endl;
        cv::cvtColor( mat, mat, cv::COLOR_GRAY2BGR );
    }
    return mat;
}
```

Obviously, I now have 3 identical histograms and unnecessarily do the optimization 3 times, but I am happy that it now works. Thank you for your help.

**Comment by taketwo** [comment] 2018-08-05 18:59
> Can I ask you to clarify that the first 6 digits represent the exposure time in ms? e.g. for an image with an exposure time of 10 ms, the file should be called 000010_000.mat?

This should be exposure time in _some_ units. Milliseconds or tenth of milliseconds, does not matter, as long as it's consistent.

> Obviously, I now have 3 identical histograms and unnecessarily do the optimization 3 times, but I am happy that it now works. Thank you for your help.

Yeah, not perfect, but does the job. Glad you've found this useful.

I've pushed several commits to prevent confusion with missing calibration data in future.

**Closed as completed by taketwo** 2018-08-05 18:59 UTC

**Comment by hieuvmphan** [comment] 2020-08-01 12:30
> Please double-check that you have the data. What I have tried just now is to wipe the contents of the `tests/data/radiometric_response_calibration` directory. Now I also get white window instead of a histogram and then a segfault. To get data you need to run `git lfs pull`.

Hi, I try to visualize the image in `tests/data/radiometric_response_calibration` to see the process. I used MATLAB to load the files but it couldn't read the files.

Can you give me some help?

Thanks.

**Comment by taketwo** [comment] 2020-08-02 08:42
These test files are `cv::Mat`s, but serialized in a custom format. If you really want to see them, you may need to write a small tool that uses https://github.com/taketwo/radical/blob/cce899af3b78a339204eab8201e67d8a6cb98b1a/include/radical/mat_io.h#L42 to load the images and then `cv::imshow()` to display them.
