### ISSUE TITLE
Result of inverseLogMap(0)

### ISSUE THREAD

**Issue by caselitz** [taketwo/radical#9] opened 2017-11-21 17:15 UTC
I noticed that `inverseLogMap(cv::Vec3b(0, 0, 0))` gives me some number (e.g. `-88.03`) on Ubuntu 14.04 with OpenCV 2 and `-inf` on 16.04 with OpenCV 3.

Is that behaviour expected? I would say the second one makes more sense.

**Comment by taketwo** [comment] 2017-11-21 17:33
Good point. Calibrated CRFs map zero intensity (or, in general, intensities below noise level) to zeros. In log-space this clearly should correspond to infinity. I used `cv::log` without taking care of such values. According to OpenCV documentation:

> Output on zero, negative and special (NaN, Inf) values is undefined.

So it's a coincidence that OpenCV 3 does what we need. I'll push a fix tomorrow.

**Comment by caselitz** [comment] 2017-11-21 17:40
Thanks for your immediate reply, looking forward to the fix. :)

**Comment by taketwo** [comment] 2017-11-22 16:53
Fixed with f60fc9aa20.

**Closed as completed by taketwo** 2017-11-22 16:53 UTC
Labels: bug

**Comment by caselitz** [comment] 2017-11-22 18:17
I haven't tested, but what I understood from your commit is that
> // Logarithm is only defined for positive numbers, everything else should map to Inf

I think this is maybe not the best thing to do. I would explicitly allow `inverseLogMap(0) = -inf` since it is nice if you can map back and forth between all representations (listed below)
- Color `[0,255]`
- Radiance `[0,1]` `=exp([-inf,0])`
- Log_Radiance `[-inf,0]` `=log([0,1])`

What should work right now is
- Radiance `[0,1]` --- DirectMap ---> Color `[0,255]`
- Color `[0,255]` --- InverseMap ---> Radiance `[0,1]`

but what I expect to be broken is (because the bold part is not true right now)
- Color `[0,255]` --- InverseLogMap ---> Log_Radiance **`[-inf,0]`**
- Log_Radiance **`[-inf,0]`** --- std::exp ---> Radiance `[0,1]` --- DirectMap ---> Color `[0,255]`

So what I mean is, it should be possible to go with a Color value of `0` through the Log_Radiance and get back to a Color value of `0`. In order to achieve this we need `inverseLogMap(0) = -inf`.

Switching between 
- Log_Radiance `[-inf,0]` --- std::exp ---> Radiance `[0,1]` 
- Radiance `[0,1]` --- std::log ---> Log_Radiance `[-inf,0]`

should be no problem as `std::exp(-std::numeric_limits<float>::infinity()) = 0` and `std::log(0.0) = -inf`. Not sure about OpenCV operations to do that on entire images? (However, I think this would be the problem of the user anyways, not of the library.)

So my suggestion would be that your quote changes to
> // Logarithm is not defined for negative numbers (which we put to NaN), 0 is -Inf

What do you think?

I'm not sure weather it makes sense to have Log_Radiance values `>0` and if this should also be restricted / checked? Depends if Colors are always assumed to be `[0,255]` and Radiance `[0,1]`?

**Comment by taketwo** [comment] 2017-11-22 19:29
I think in my projects I always explicitly filter out invalid pixels so never faced this problem. But what you propose makes sense and if this is the behavior which helps in your application, then let's do this way.

> Not sure about OpenCV operations to do that on entire images? (However, I think this would be the problem of the user anyways, not of the library.)

OpenCV docs say that for `log()` the output is undefined and for `exp()` "special values (NaN, Inf) are not handled". In case of `log()` this does not matter for us, because a pre-computed LUT is used. As for `exp()`, well that would be user's problem indeed.

> Depends if Colors are always assumed to be [0,255] and Radiance [0,1]? 

Calibration app bundled with this library always outputs radiance in `[0,1]` range. However, I don't see any reason to explicitly assume this in the `RadiometricResponse` class. In some papers I saw people using `[0,255]` range for radiances.

**Comment by caselitz** [comment] 2017-11-22 19:51
> I think in my projects I always explicitly filter out invalid pixels so never faced this problem.

So you consider pixels with color 0 (and 255) invalid as you cannot obtain a meaningful radiance value from them? I agree, but there can still be situations where you do not want to discard the information ("radiance smaller (bigger) than") they provide.

> But what you propose makes sense and if this is the behavior which helps in your application, then let's do this way.

I would appreciate this. :)


Ok, seems that `cv::exp()` and `cv::log()` are not suited for the conversion between Radiance and Log_Radiance. So, the user who wants to do this can use `std::exp()` and `std::log()` or has to figure out something else.

I agree regarding the radiance ranges.

**Comment by taketwo** [comment] 2017-11-22 20:46
Pushed one more commit, should be `-Inf` now.

> I agree, but there can still be situations where you do not want to discard the information ("radiance smaller (bigger) than") they provide.

Yep, such values deserve a special treatment and I make a lot of use of them. In case you're interested, my [last paper](https://www.dropbox.com/s/9g4nwemleyvs8je/alexandrov_2017_cvww.pdf?dl=0) on the topic.

**Comment by caselitz** [comment] 2017-11-22 20:54
> Pushed one more commit, should be -Inf now.

Thank you!

> Yep, such values deserve a special treatment and I make a lot of use of them. In case you're interested, my last paper on the topic.

Thanks for the hint, but I know it already. ;) Very interesting work!

**Comment by taketwo** [comment] 2017-11-22 20:59
Ah so. Well, thanks :)

**Comment by caselitz** [comment] 2017-12-08 17:29
Btw. I think one of the last commits related to this issue here introduced a warning (gcc), maybe you want to fix it?

> [path]/radical/src/radical/radiometric_response.cpp:51:50: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses] cv::Mat_<bool> positive = response_.reshape(1) > 0.0f & response_.reshape(1) != Inf;

**Comment by taketwo** [comment] 2017-12-08 17:39
Thanks for the heads-up, fixed!

**Comment by caselitz** [comment] 2018-02-05 20:05
Hi again! :)

I don't know why, but the inf issue is back. I just noticed it, but don't know what changed in the meantime, maybe gcc or opencv version (currently I'm on opencv-3.3.1 from ROS Kinetic, Ubuntu 16.04.03).

It's related to this piece of code: https://github.com/taketwo/radical/blob/master/src/radical/radiometric_response.cpp#L52-L60
Apparently, I've the same issue you described for MSVC - but with gcc 5.4.0. Interestingly, it only happens when the optional mask of `setTo` is used.

...can you reproduce this behavior?

Is there a reason not to make the code for MSVC default? Is it slower?

Best, Tim

**Comment by taketwo** [comment] 2018-02-15 16:25
Hi, thanks for letting me know and sorry for the delay.

I can reproduce the issue with the same OpenCV as you have and with different compilers (gcc 5.4.0, gcc 7, clang 5). And also with the newest OpenCV 3.4.0 and gcc 5.4.0. So I suppose something has changed and this change is gonna stay. So is worth fixing :)

I haven't done any performance comparisons, it's just that the "MSVC code" looks a bit more verbose. But it seems to work consistently and is anyway a small loop that runs a single time in a constructor, so nobody cares. I made it the default code in 9dbaa2b94.
